### ISSUE TITLE
error messages ruining the aesthetics

### ISSUE THREAD

**Issue by chillmatin** [talwat/lowfi#1]
![image](https://github.com/user-attachments/assets/7b6eea22-1e90-4143-8bfe-25d4e07342d8)
player works just fine, it just shows some error messages which sort of ruins  the experience.

**Comment by chillmatin** [comment]
i am using arch linux btw, and pipewire for audio

**Comment by talwat** [comment]
Yeah, this happens for me too. When I was testing it on my PC I just used an "alternate screen" which just meant the rest of your terminal history (and the errors) wouldn't be visible. I'll probably add a flag which does this, and enable that flag by default on Linux.

The problem is these errors come from rodio, specifically the c library it uses, and so I have no idea how to disable them. I'll look into the latter, but otherwise I'll implement the former later today.

**Comment by talwat** [comment]
Fixed with https://github.com/talwat/lowfi/commit/fd2d37d6357e9ab113f5970c90cc6aec19057fdf, although I'll keep this open until confirmation.

AUR should be updated relatively soon.

**Comment by chillmatin** [comment]
wow it got solved pretty quickly. It works like a charm now. Thanks for the chill beats experience!

**Comment by chillmatin** [comment]
![image](https://github.com/user-attachments/assets/f4b3e373-ca1d-4bef-b8ad-0fca80a7d2ee)
issue still persists

**Comment by talwat** [comment]
That is very strange... Can you show me `lowfi --version`?

**Comment by talwat** [comment]
Well, I've tried to improve the solution, and I've added the `--alternate` flag as an implementation of the first solution just in case.

**Comment by chillmatin** [comment]
![image](https://github.com/user-attachments/assets/b6d1cf63-fc0d-49d6-85b5-033156d20a2b)

**Comment by talwat** [comment]
I haven't updated the AUR yet, so that could be why. Also yeah I disabled `version` for some strange reason but that should also now be fixed. My apologies 😅

**Comment by chillmatin** [comment]
updated the aur package, it works now.
![image](https://github.com/user-attachments/assets/ac6ca32b-54ab-4df7-86e4-6cfc7964f4a0)
just before opening such error pops up but then it returns back looking normal which is fine but can be improved with a flag like --verbose

**Comment by chillmatin** [comment]
![image](https://github.com/user-attachments/assets/7b94fc9d-9ac6-4f1d-8f21-38fbf2e335c7)
then it turns into this which is great
